apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "perses.fullname" . }}
  labels:
    {{- include "perses.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |-
    security:
      readonly: {{ .Values.config.security.readOnly }}
      {{- if and .Values.config.security.encryptionKeyFile .Values.config.security.encryptionKey }}
      encryption_key_file: {{ printf "%s/key" (.Values.config.security.encryptionKeyFile | trimSuffix "/") }}
      {{- end }}
      {{- if and (not .Values.config.security.encryptionKeyFile) .Values.config.security.encryptionKey }}
      encryption_key: {{ .Values.config.security.encryptionKey }}
      {{- end }}
      enable_auth: {{ .Values.config.security.enableAuth }}

    database:
      {{- with .Values.config.database.file }}
      file:
        {{- toYaml . | nindent 8 }}
      {{ end -}}

      {{- with .Values.config.database.sql }}
      sql:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{ end -}}

    {{- with .Values.config.important_dashboards }}
    important_dashboards:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.schemas }}
    schemas:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.provisioning }}
    provisioning:
      {{- toYaml . | nindent 6 }}
    {{- end }}
