{{- if .Values.config.security.encryptionKeyFile }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perses.fullname" . }}-encryption-key
  labels:
    {{- include "perses.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  key: {{ .Values.config.security.encryptionKey | b64enc }}
{{- end }}

---
